version: "3.9"

networks:
  notifyx-net:
    driver: bridge

volumes:
  mongo_data:
  kafka_data:
  localstack_data:
  redis_data:

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - notifyx-net

  kafka:
    image: apache/kafka:3.9.0
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      # KRaft Mode
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # Listeners
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Storage directory
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

      # Auto-create topics (optional)
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - notifyx-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - notifyx-net
    command: redis-server --appendonly yes

  localstack:
    image: localstack/localstack:3.3
    restart: unless-stopped
    environment:
      - SERVICES=sqs,sns,secretsmanager,s3
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=0
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - ./infrastructure/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh:ro
    networks:
      - notifyx-net

  oauth:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.7
    restart: unless-stopped
    environment:
      - SERVER_PORT=8081
      - JSON_CONFIG_PATH=/config/config.json
    volumes:
      - ./infrastructure/mock-oauth/config.json:/config/config.json:ro
    ports:
      - "8081:8081"
    networks:
      - notifyx-net
