http:
  addr: ":8080"

oauth:
  issuer: "http://localhost:8081/default"
  jwks: "http://localhost:8081/default/jwks"
  audiences: []

storage:
  mongo:
    uri: "mongodb://localhost:27017"
    database: "notifyx"

